Excluded getTemperatureZ() because it was causing a failure
Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "run-main-5"
[error] Nonzero exit code: 1
[error] (Compile / runMain) Nonzero exit code: 1
[error] Total time: 21 s, completed Aug 19, 2021 3:18:41 PM